root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"  
  cmd = "go build -o tmp/main ."  
  include_ext = ["go"]  
  exclude_dir = ["tmp", ".github", ".vscode", "actions-runner", "Git"]
  watch_dir = ["." ]

[log]
  level = "info"