version: '3.8'

services:
  grade-portal-be-go-2:
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=${MONGO_URL}
    env_file:
      - .env
    volumes:
      - .:/app
    image: nguyentrongkha2k4/grade-portal-be-go-2

