services:
  grade-portal-be-go-2:
    image: nguyentrongkha2k4/grade-portal-be:latest
    pull_policy: always   # Luôn pull image mới nhất từ Docker Hub
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=${MONGO_URL}
    env_file:
      - .env
    volumes:
      - .:/app
