name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23  

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: go mod tidy

      # Bước 4: Kiểm tra format code
      - name: Check code format
        run: go fmt ./...

      # Bước 5: Chạy tests
      - name: Run tests
        run: go test ./... -v
