name: go2

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Build and Push Docker Image
        run: |
          # Sử dụng Secrets để login DockerHub
          echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          sudo docker-compose build app
          sudo docker-compose push app

      - name: Deploy Application
        run: |
          # Sử dụng Secrets để deploy ứng dụng
          sudo docker-compose pull app
          sudo docker-compose down    
          sudo docker-compose up -d
