name: go2

on:
  push:
    branches: 
    - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
      - name: Build and Push Dockerfile
        run: |
          echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          cd src/
          sudo docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/go2 .
          sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/go2

  deploy:
    needs: docker 
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/go2:latest
      - name: Delete old container
        run: sudo docker rm -f learngo
      - name: Run Docker container
        run: |
          cd ~
          sudo docker run -d -p 8080:8080 --name learngo --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/go2
