name: go2
on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Push Docker Image
        run: |
          # Đăng nhập Docker Hub
          echo "`" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          # Xây dựng và đẩy Docker Image
          cd src/
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/go2 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/go2

  deploy:
    needs: docker
    runs-on: ubuntu-latest 
    steps:
      - name: Pull Docker image
        run: |
          # Kéo image mới nhất từ Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/go2:latest
      - name: Stop and Remove old container
        run: |
          docker stop go2 || true
          docker rm go2 || true
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name go2 --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/go2:latest
