name: go2
on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: self-hosted  # Chạy trên self-hosted runner (máy Mac)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Push Docker Image
        run: |
          # Đăng nhập Docker Hub
          echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          # Xây dựng và đẩy Docker Image
          cd src/
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/go2 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/go2

  deploy:
    needs: docker
    runs-on: self-hosted  # Chạy trên self-hosted runner (máy Mac)
    steps:
      - name: Pull Docker image
        run: |
          # Kéo image mới nhất từ Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/go2:latest

      - name: Delete old container
        run: |
          # Xóa container cũ nếu có
          docker rm -f go2

      - name: Run Docker container
        run: |
          # Chạy container mới với cổng 8080
          docker run -d -p 8080:8080 --name go2 --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/go2
